Repository dotnet/roslyn-analyzers, pull requests merged in 2022-12, with the labels that each got.

#6303 Add readme for Microsoft.CodeAnalysis.NetAnalyzers package
  eng/GenerateAnalyzerNuspec.targets
  nuget/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.Package.csproj
  src/NetAnalyzers/readme.md
  src/Tools/GenerateAnalyzerNuspec/Program.cs
Labels: Area-Infrastructure

#6360 Add file-local class test for CA1812
  src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidUninstantiatedInternalClassesTests.cs
Labels: Community

#6363 Move from .NET 7 RC1 to .NET 7.0.101
  eng/Versions.props
  global.json
  src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/DoNotRaiseReservedExceptionTypes.cs
  src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/PreferDictionaryContainsMethods.cs
  src/NetAnalyzers/Core/Microsoft.NetFramework.Analyzers/Helpers/SyntaxNodeHelper.cs
  src/PerformanceTests/Utilities/ReferenceAssemblies/ResourceLoader.cs
  src/PublicApiAnalyzers/Core/Analyzers/DeclarePublicApiAnalyzer.cs
  src/Tools/GenerateDocumentationAndConfigFiles/JsonWriter.cs
  src/Utilities.UnitTests/FlowAnalysis/Analysis/PropertySetAnalysis/PropertySetAnalysisTests.cs
  src/Utilities/Compiler/Extensions/IOperationExtensions.cs
  src/Utilities/Compiler/WordParser.cs
  src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PropertySetAnalysis/PropertySetAnalysis.PropertySetDataFlowOperationVisitor.TrackedAssignmentData.cs
  src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PropertySetAnalysis/PropertySetAnalysis.PropertySetDataFlowOperationVisitor.cs
  src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/PropertySetAnalysis/PropertySetAnalysis.cs
  src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/TaintedDataAnalysis/TaintedDataAnalysis.TaintedDataOperationVisitor.cs
  src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/TaintedDataAnalysis/TaintedDataSymbolMapExtensions.cs
  src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/AnalysisEntityDataFlowOperationVisitor.cs
  src/Utilities/FlowAnalysis/SingleThreadedConcurrentDictionary.cs
Labels: Area-Infrastructure

#6319 Update "Getting Started" section with VS 2022 requirement
  README.md
Labels: Documentation

#6347 Update "Branch Definitions" documentation
  docs/NetCore_GettingStarted.md
Labels: Documentation

#6367 Remove rulesets
  .editorconfig
  Directory.Build.targets
  eng/Analyzers_NonShippingRules.ruleset
  eng/Analyzers_ShippingRules.ruleset
  eng/globalconfigs/Common.globalconfig
  eng/globalconfigs/NonShipping.globalconfig
  eng/globalconfigs/Shipping.globalconfig
  src/Directory.Build.props
  src/Directory.Build.targets
  src/Microsoft.CodeAnalysis.Analyzers/UnitTests/MetaAnalyzers/SymbolIsBannedInAnalyzersTests.cs
  src/NetAnalyzers/CSharp/Microsoft.NetCore.Analyzers/InteropServices/CSharpDisableRuntimeMarshalling.Fixer.IdentifierGenerator.cs
  src/NetAnalyzers/CSharp/Microsoft.NetCore.Analyzers/Runtime/CSharpForwardCancellationTokenToInvocationsFixer.TypeNameVisitor.cs
  src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/DoNotDeclareProtectedMembersInSealedTypes.cs
  src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Performance/UseAsSpanInsteadOfRangeIndexer.cs
  src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/BufferBlockCopyLengthAnalyzer.cs
  src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/DetectPreviewFeatureAnalyzer.cs
  src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/SpecifyCultureForToLowerAndToUpper.cs
  src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/UseNameOfInPlaceOfStringTests.cs
  src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/InteropServices/DisableRuntimeMarshallingTests.cs
  src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/SpecifyIFormatProviderTests.cs
  src/Test.Utilities/Test.Utilities.csproj
Labels: Area-Infrastructure
