Repository dotnet/roslyn-analyzers, pull requests merged in 2024-08, with the labels that each got.

#7335 Highlight C# code in unit tests
  src/Test.Utilities/CSharpCodeFixVerifier`2.cs
  src/Test.Utilities/CSharpCodeRefactoringVerifier`1.cs
  src/Test.Utilities/CSharpSecurityCodeFixVerifier`2.cs
Labels: Community

#7347 CA2213: Handle overriden `DisposeCoreAsync` / `DisposeAsyncCore`
  src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/DisposableFieldsShouldBeDisposedTests.cs
  src/Utilities/Compiler/Extensions/IMethodSymbolExtensions.cs
Labels: Community

#7377 Change localization branch to release/9.0.1xx temporarily
  azure-pipelines-microbuild.yml
Labels: Area-Infrastructure

#7379 Bump main to 10.0
  eng/Versions.props
  src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.sarif
Labels: Area-Infrastructure

#7286 fix(CA2023: Adds validation against invalid braces in logger message templates)
  src/NetAnalyzers/Core/AnalyzerReleases.Unshipped.md
  src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/MicrosoftCodeQualityAnalyzersResources.resx
  src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.cs.xlf
  src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.de.xlf
  src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.es.xlf
  src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.fr.xlf
  src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.it.xlf
  src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.ja.xlf
  src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.ko.xlf
  src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.pl.xlf
  src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.pt-BR.xlf
  src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.ru.xlf
  src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.tr.xlf
  src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.zh-Hans.xlf
  src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/xlf/MicrosoftCodeQualityAnalyzersResources.zh-Hant.xlf
  src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/LoggerMessageDefineAnalyzer.cs
  src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.md
  src/NetAnalyzers/Microsoft.CodeAnalysis.NetAnalyzers.sarif
  src/NetAnalyzers/RulesMissingDocumentation.md
  src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/LoggerMessageDefineTests.cs
  src/Utilities/Compiler/DiagnosticCategoryAndIdRanges.txt
Labels: Community

#7261 CA1854: Use unused variable name for out parameter
  src/NetAnalyzers/CSharp/Microsoft.NetCore.Analyzers/Performance/CSharpPreferDictionaryTryMethodsOverContainsKeyGuardFixer.cs
  src/NetAnalyzers/RulesMissingDocumentation.md
  src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Performance/PreferDictionaryTryGetValueMethodsTests.cs
  src/NetAnalyzers/VisualBasic/Microsoft.NetCore.Analyzers/Performance/BasicPreferDictionaryTryMethodsOverContainsKeyGuardFixer.vb
  src/Utilities/Workspaces/SyntaxGeneratorExtensions.cs
Labels: Community

#7397 [release/9.0.1xx] Update AnalyzerReleases file to reflect new analyzers for .NET9 release
  src/NetAnalyzers/Core/AnalyzerReleases.Shipped.md
  src/NetAnalyzers/Core/AnalyzerReleases.Unshipped.md
Labels: servicing-approved

#7306 Improve CA1305 for nullable types
  src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/SpecifyIFormatProvider.cs
  src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/SpecifyIFormatProviderTests.cs
Labels: Community

#7244 Do not suggest passing IFormatProvider to certain Convert methods
  src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/SpecifyIFormatProvider.cs
  src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Runtime/SpecifyIFormatProviderTests.cs
Labels: Community
